import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Menu, X, ArrowRight, MapPin, Phone, Mail, ChevronRight, Sprout, Egg, Stethoscope, Fish, FlaskConical, GraduationCap, Factory, ShieldCheck, MessageCircle, Send, Leaf, Wheat, Users } from 'lucide-react';
import './style.css';
import l1 from '../location/l1.jpg';
import l2 from '../location/l2.jpg';
import l3 from '../location/l3.jpg';
import l4 from '../location/l4.jpg';
import l5 from '../location/l5.jpg';

const locationImages = [l1, l2, l3, l4, l5];

const data = {
  fr: {
    nav: ['Accueil', 'À propos', 'Activités', 'Produits', 'Partenaires', 'Actualités', 'Galerie', 'Contact'],
    home: 'Accueil', discover: 'Découvrir nos activités', contact: 'Nous contacter',
    kicker: 'SIAEDTS-SARL · MACENTA, GUINÉE',
    title: 'L’agro-élevage au service du développement durable.',
    intro: 'Une entreprise industrielle agro-livestock engagée pour une production responsable, l’innovation appliquée et des partenariats qui font avancer la Guinée.',
    trusted: 'Nos domaines d’expertise',
    aboutTitle: 'Cultiver le potentiel. Élever l’avenir.',
    aboutText: 'Établie à Macenta Centre, Bamala, en Région Forestière de Nzérékoré, SIAEDTS-SARL rassemble expertise agricole, élevage et services techniques dans une même ambition de développement durable.',
    location: 'Macenta Centre, Bamala · Région Forestière de Nzérékoré · Guinée',
    learn: 'En savoir plus',
    activities: 'Nos activités', actLead: 'Une expertise intégrée, de l’étude du terrain jusqu’à la formation des équipes.',
    products: 'Nos produits', prodLead: 'Des solutions de qualité pour les professionnels, producteurs et communautés.',
    viewProducts: 'Voir tous les produits', partners: 'Nos partenaires', partnerLead: 'Nous cherchons à bâtir des collaborations solides, nationales et internationales.',
    international: 'Partenaires internationaux', national: 'Partenaires nationaux',
    nationalText: 'Ministères et ONG partenaires — liste détaillée à confirmer avec SIAEDTS-SARL.',
    news: 'Actualités & initiatives', newsLead: 'Suivez les projets, activités et avancées de SIAEDTS-SARL.',
    placeholder: 'Contenu à venir', gallery: 'En images', galleryLead: 'Photos des exploitations, équipes et activités — galerie à compléter avec les visuels officiels.',
    contactTitle: 'Parlons de votre projet.', contactLead: 'Une question sur nos produits, nos activités ou un partenariat ? Écrivez-nous.',
    address: 'Adresse', addressText: 'Macenta Centre, Bamala, Guinée',
    details: 'Coordonnées à confirmer', formName: 'Votre nom', formEmail: 'Votre e-mail', formMessage: 'Comment pouvons-nous vous aider ?', send: 'Envoyer le message',
    footer: 'Industrial Agro-Livestock Company', rights: 'Prototype de site web · Tous droits réservés.',
  },
  en: {
    nav: ['Home', 'About', 'Activities', 'Products', 'Partners', 'News', 'Gallery', 'Contact'], home: 'Home', discover: 'Explore our activities', contact: 'Contact us',
    kicker: 'SIAEDTS-SARL · MACENTA, GUINEA', title: 'Agro-livestock in service of sustainable development.', intro: 'An industrial agro-livestock company advancing responsible production, applied innovation and partnerships that move Guinea forward.', trusted: 'Our areas of expertise',
    aboutTitle: 'Cultivating potential. Raising the future.', aboutText: 'Based in Macenta Centre, Bamala, in Guinea’s Forest Region of Nzérékoré, SIAEDTS-SARL brings together agricultural expertise, livestock farming and technical services around one sustainable-development ambition.', location: 'Macenta Centre, Bamala · Forest Region of Nzérékoré · Guinea', learn: 'Learn more',
    activities: 'Our activities', actLead: 'Integrated expertise, from land studies to team training.', products: 'Our products', prodLead: 'Quality solutions for professionals, producers and communities.', viewProducts: 'View all products', partners: 'Our partners', partnerLead: 'We aim to build robust national and international collaborations.', international: 'International partners', national: 'National partners', nationalText: 'Partner ministries and NGOs — detailed list to be confirmed with SIAEDTS-SARL.', news: 'News & initiatives', newsLead: 'Follow SIAEDTS-SARL projects, activities and progress.', placeholder: 'Coming soon', gallery: 'In pictures', galleryLead: 'Photos of farms, teams and activities — gallery to be completed with official visuals.', contactTitle: 'Let’s discuss your project.', contactLead: 'A question about our products, activities or a partnership? Write to us.', address: 'Address', addressText: 'Macenta Centre, Bamala, Guinea', details: 'Contact details to be confirmed', formName: 'Your name', formEmail: 'Your email', formMessage: 'How can we help?', send: 'Send message', footer: 'Industrial Agro-Livestock Company', rights: 'Website prototype · All rights reserved.'
  }
};
const activities = [
  [Factory, 'Industrie', 'Industrial operations', 'Valorisation et production agro-livestock — détails à préciser.'], [Sprout, 'Gestion des terres cultivables', 'Cultivable land management', 'Études, gestion et mise en valeur des terres cultivables.'], [FlaskConical, 'Recherche appliquée en élevage', 'Applied livestock research', 'Recherche appliquée au développement des filières d’élevage.'], [Stethoscope, 'Produits vétérinaires & intrants', 'Veterinary products & inputs', 'Importation et exportation de produits vétérinaires et intrants agricoles.'], [GraduationCap, 'Formation', 'Training', 'Renforcement de compétences pour les professionnels et communautés.'], [ShieldCheck, 'Santé & sécurité', 'Health & safety', 'Accompagnement et sensibilisation santé et sécurité.']
];
const products = [[Egg, 'Œufs de table', 'Table eggs'], [Egg, 'Poussins de chair', 'Broiler chicks'], [Egg, 'Poussins pondeuses d’un jour', 'Layer day-old chicks'], [Stethoscope, 'Produits vétérinaires', 'Veterinary products'], [Wheat, 'Aliments & concentrés volaille', 'Poultry feed & concentrates'], [Sprout, 'Céréales & produits agricoles', 'Cereals & farm produce'], [Leaf, 'Huiles essentielles & produits naturels', 'Essential oils & natural products'], [Fish, 'Produits aquacoles', 'Aquaculture products']];
function App() {
  const [lang, setLang] = useState('fr'), [menu, setMenu] = useState(false), [sent, setSent] = useState(false), [img, setImg] = useState(0); const t = data[lang]; const scroll = (id) => { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); setMenu(false) }; const navIds = ['home', 'about', 'activities', 'products', 'partners', 'news', 'gallery', 'contact'];
  React.useEffect(() => { const id = setInterval(() => setImg(i => (i + 1) % locationImages.length), 3000); return () => clearInterval(id); }, []);
  return <><header><button className="brand" onClick={() => scroll('home')}><span className="mark">S</span><span><b>SIAEDTS</b><small>SARL</small></span></button><nav className={menu ? 'open' : ''}>{t.nav.map((n, i) => <button key={n} onClick={() => scroll(navIds[i])}>{n}</button>)}</nav><div className="topActions"><div className="language"><button className={lang === 'fr' ? 'active' : ''} onClick={() => setLang('fr')}>FR</button><span>/</span><button className={lang === 'en' ? 'active' : ''} onClick={() => setLang('en')}>EN</button></div><button className="menu" onClick={() => setMenu(!menu)} aria-label="Menu">{menu ? <X /> : <Menu />}</button></div></header>
    <main><section className="hero" id="home"><div className="heroGlow" /><div className="heroContent"><p className="eyebrow"><span /> {t.kicker}</p><h1>{t.title}</h1><p className="heroIntro">{t.intro}</p><div className="heroButtons"><button className="btn gold" onClick={() => scroll('activities')}>{t.discover}<ArrowRight size={18} /></button><button className="btn outline" onClick={() => scroll('contact')}>{t.contact}</button></div></div><div className="heroVisual"><div className="circle"></div><div className="farmCard"><Sprout size={30} /><span>AGRO · ÉLEVAGE</span><b>Guinée</b></div></div><div className="scrollHint">SCROLL <span /></div></section>
      <section className="introSection" id="about"><div className="imagePanel"><div className="field" style={{ backgroundImage: `url(${locationImages[img]})`, backgroundSize: 'cover', backgroundPosition: 'center', backgroundRepeat: 'no-repeat' }}><span></span><span></span><span></span></div><div className="locationTag"><MapPin size={18} />{t.location}</div></div><div className="aboutCopy"><p className="eyebrow green">01 · SIAEDTS-SARL</p><h2>{t.aboutTitle}</h2><p>{t.aboutText}</p><button className="textLink" onClick={() => scroll('contact')}>{t.learn}<ChevronRight size={18} /></button></div></section>
      <section className="expertise"><p className="sectionLabel">{t.trusted}</p><div className="expertiseRow"><span><Sprout />Agro-élevage</span><span><Stethoscope />Vétérinaire</span><span><Fish />Aquaculture</span><span><FlaskConical />Recherche</span><span><GraduationCap />Formation</span></div></section>
      <section className="section activities" id="activities"><div className="sectionHeading"><div><p className="eyebrow green">02 · EXPERTISE</p><h2>{t.activities}</h2></div><p>{t.actLead}</p></div><div className="activityGrid">{activities.map(([Icon, fr, en, desc], i) => <article className="activityCard" key={fr}><span className="number">0{i + 1}</span><Icon /><h3>{lang === 'fr' ? fr : en}</h3><p>{desc}</p><ArrowRight className="cardArrow" size={18} /></article>)}</div></section>
      <section className="productsBand" id="products"><div className="sectionHeading"><div><p className="eyebrow light">03 · OFFRE</p><h2>{t.products}</h2></div><p>{t.prodLead}</p></div><div className="productGrid">{products.map(([Icon, fr, en]) => <div className="product" key={fr}><div className="productIcon"><Icon /></div><h3>{lang === 'fr' ? fr : en}</h3><button onClick={() => scroll('contact')}>{t.contact}<ArrowRight size={15} /></button></div>)}</div><button className="btn gold centered" onClick={() => scroll('contact')}>{t.viewProducts}<ArrowRight size={18} /></button></section>
      <section className="section partners" id="partners"><div className="sectionHeading"><div><p className="eyebrow green">04 · COLLABORATION</p><h2>{t.partners}</h2></div><p>{t.partnerLead}</p></div><div className="partnerLayout"><div><p className="partnerTitle">{t.international}</p><div className="partnerGrid">{['Vitalac SA · France', 'Medivet SA · Tunisie', 'Laboratoire Biotest · Ukraine', 'FAO', 'OMSA', 'OMS'].map(x => <div className="partner" key={x}>{x}</div>)}</div></div><div className="nationalPartner"><Users /><p className="partnerTitle">{t.national}</p><p>{t.nationalText}</p><small>◦ {t.placeholder}</small></div></div></section>
      <section className="newsSection" id="news"><div className="sectionHeading"><div><p className="eyebrow green">05 · À LA UNE</p><h2>{t.news}</h2></div><p>{t.newsLead}</p></div><div className="newsGrid">{['Projets de développement', 'Recherche & innovation', 'Vie de l’entreprise'].map((x, i) => <article key={x} className={'newsCard n' + i}><span>0{i + 1} · {t.placeholder}</span><h3>{x}</h3><button>{t.learn}<ArrowRight size={17} /></button></article>)}</div></section>
      <section className="gallery" id="gallery"><div className="galleryCopy"><p className="eyebrow light">06 · GALERIE</p><h2>{t.gallery}</h2><p>{t.galleryLead}</p></div><div className="galleryTiles"><div /><div /><div /><div /></div></section>
      <section className="contactSection" id="contact"><div className="contactInfo"><p className="eyebrow green">07 · CONTACT</p><h2>{t.contactTitle}</h2><p>{t.contactLead}</p><div className="contactDetails"><span><MapPin />{t.address}<b>{t.addressText}</b></span><span><Phone />{t.details}<b>—</b></span><span><Mail />{t.details}<b>—</b></span></div></div><form onSubmit={e => { e.preventDefault(); setSent(true) }}><input required placeholder={t.formName} /><input type="email" required placeholder={t.formEmail} /><textarea required placeholder={t.formMessage} rows="5" /><button className="btn gold" type="submit">{sent ? '✓ ' + (lang === 'fr' ? 'Message préparé' : 'Message ready') : t.send}<Send size={17} /></button><small>{lang === 'fr' ? 'Prototype : ce formulaire ne transmet pas encore de message.' : 'Prototype: this form does not send messages yet.'}</small></form></section></main>
    <footer><button className="brand"><span className="mark">S</span><span><b>SIAEDTS</b><small>SARL</small></span></button><p>{t.footer}</p><p>© 2026 SIAEDTS-SARL · {t.rights}</p></footer></>
}
createRoot(document.getElementById('root')).render(<App />);
